### PR TITLE
[WIP] - Added documentation for environment vars and Vagrantfile configuration

### PR DESCRIPTION
**Pull request by njgrisafi**
Added basic documentation for environment variables. Also, adds the environment variables to the Vagrantfile.

A developer can manually configure the **HOST** and **PORT* variables in the Vagrantfile.

### CODE REVIEW

**Comment by mrpudn** [comment]
Hmm, I'm wondering if a private network configuration is a better solution to the port forwarding problem:
https://www.vagrantup.com/docs/networking/private_network.html

As you've got it, you'd have to change your `Vagrantfile` to change where the app listens, which might be a pain. People might accidentally check in those changes to their `Vagrantfile`, too.

Also, added some quick documentation for the env vars in #60.

**Comment by njgrisafi** [comment]
@mrpudn ahh my bad didn't see that! We can just close this PR and I can open a new one for the private networks if that works out

**Comment by mrpudn** [comment]
No worries, we can keep this open until you have some time to explore the private networks. We can close it if we need to go back to the drawing board

**Comment by njgrisafi** [comment]
@mrpudn sounds good! Let's keep this open for now

**Comment by njgrisafi** [comment]
I'll remove those documentation commits too

**Comment by mrpudn** [comment]
hey @njgrisafi I'm going to go ahead and close this, but feel free to create a PR if you get back to this :)

**Pull request closed without merging**
